### ISSUE TITLE
[META} Packaging

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#10137]
# Very old versions 

- [ ] MacPorts - very old version (1.2.1) https://github.com/macports/macports-ports/tree/master/devel/radare2
 - [ ] Funtoo - very old version (2.0.1) https://github.com/funtoo/dev-kit/tree/master/dev-util/radare2
 - [ ] GoboLinux - very old version (1.1.0) https://github.com/gobolinux/Recipes/tree/master/trunk/Radare2/1.1.0
 - [ ] Hyperbola - very old version (1.4.0) https://www.hyperbola.info/packages/?q=radare2
 - [ ] OpenBSD - super old version (0.10.6) http://openports.se/devel/radare2/main
 - [ ] Trisquel linux - 0.9.6 version. No comments 

# Missing packages

- [ ] Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1368855
- [ ] OpenSUSE
- [ ] Linux Mint
- [ ] Mageia https://bugs.mageia.org/show_bug.cgi?id=23064
- [ ] ALT Linux https://bugzilla.altlinux.org/show_bug.cgi?id=34927
- [ ] ROSA Linux https://bugzilla.rosalinux.ru/show_bug.cgi?id=9008
- [ ] Astra Linux

**Comment by radare** [comment]
voidlinux

**Comment by XVilka** [comment]
@radare Voidlinux what?

**Comment by radare** [comment]
theres no voidlinux in the badge

**Comment by XVilka** [comment]
@radare it is because VoidLinux not yet merged in this repology tool: https://github.com/repology/repology/pull/400

**Comment by XVilka** [comment]
I wrote an email to OpenBSD maintainer but no response. If you have other means to ping them - please do.

**Comment by XVilka** [comment]
https://github.com/radare/radare2/issues/10428

**Comment by simos** [comment]
By adding the snap package of radare2 (#10428), it will cover the following distributions:
1.  Arch Linux
2.  Debian
3.  elementary OS
4.  Fedora
5.  Gentoo
6.  Linux Mint
7.  Manjaro
8.  OpenEmbedded/Yocto
9.  openSUSE
10. OpenWrt
11. Solus
12. Raspbian
13. Ubuntu

Multiply that to the following four architectures: i386, amd64, armhf and arm64.
In practice, more distributions are able to install those packages. See a live example of the Skype snap package at https://snapcraft.io/skype and the distribution stats at the end of the page.

I am also interested in packaging Cutter. That will come at a latter date.

I can take care of issues that may arise from the packaging and respond to them on github (you can ping me in those reports).

For testing, you can try my unofficial package (only for amd64) at https://snapcraft.io/radare2-simosx
I'll remove my unofficial package once the official radare2 snap package is released.

**Comment by devnexen** [comment]
@XVilka we re going to update OpenBSD version finally ;-) straight to the 3.0.1 release.

**Comment by XVilka** [comment]
Also would be nice to add radare2 package in DragonFlyBSD DPorts repository: https://github.com/DragonFlyBSD/DPorts

**Comment by devnexen** [comment]
The proper repository to contribute is more this one https://github.com/DragonFlyBSD/DeltaPorts, but there seemingly already an attempt https://github.com/DragonFlyBSD/DeltaPorts/blob/master/ports/devel/radare2/STATUS (ie most of dragonflybsd ports are "copy/paste" of FreeBSD's as possible).

**Comment by XVilka** [comment]
@devnexen could you please try to update radare2 to 4.5.0 in these DeltaPorts?

**Comment by devnexen** [comment]
Thanks for the reminder, as first step I did a PR to minimize local dports patching (and fix the build in the process anyway).

**Comment by XVilka** [comment]
@devnexen I did https://github.com/radareorg/radare2/pull/17470 also I think it's possible to update the package in DragonFly to 4.5.0.
We also plan the patch release 4.5.1 soon: https://github.com/radareorg/radare2/milestone/57

Tell me if the patch is required so I can cherry-pick it to the 4.5.1 branch.

**Comment by XVilka** [comment]
@devnexen since you also improved Illumos/Solaris support, please consider to publish it also in [OpenIndiana](https://www.openindiana.org/packages/) package repository:
- http://docs.openindiana.org/dev/userland/
- https://github.com/OpenIndiana/oi-userland/tree/oi/hipster/components

**Comment by q2dg** [comment]
I've notice radare2 package in Ubuntu has dissapeared from "hirsute" version (21.04). See this:
https://packages.ubuntu.com/search?suite=**hirsute**&searchon=names&keywords=radare2
and this, instead:
https://packages.ubuntu.com/search?suite=**groovy**&searchon=names&keywords=radare2
Do you know the reason?
Thanks!

**Comment by radare** [comment]
Thanks for the heads up on this. I waited a bit to see if someone would reply. But I don’t know which are the actual reasons for this.

I’ll contact the maintainer
