### ISSUE TITLE
[TRACKER] Windows support

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1194]
# Build and Compatibility support

- [ ] ~~Building in MSYS2 / Mingw-w64 [[1]](https://github.com/radare/sdb/issues/62)~~
- [ ] make symstall using NTFS symlinks
- [x] Add support to be built in Windows using clang-cl? https://github.com/radare/radare2/issues/10115
- [ ] ~~Using [cccl](https://github.com/swig/cccl) - MSVC wrapper to be able to build using MSVC from unchanged Makefile.~~
- [x] Make testsuite pass on Windows
- [ ] Make zignatures work for Windows libraries 
- [x] Windows 64-bit only build, without using 32bit API and libraries.
- [x] ~~Building in Cygwin32~~
- [x] ~~Building in Cygwin64~~
- [x] ~~Building in Mingw32 https://github.com/radare/radare2/issues/1099~~
- [x] ~~Building in MSYS~~
- [x] ~~Visual mode in Cygwin and MIngw32 consoles (doesn't allow scrolling) (applicable for mintty, conemu) https://github.com/radare/radare2/issues/1488~~

# Code Refactoring

- [x] Unicode compatibility on Windows https://github.com/radare/radare2/issues/7235
- [x] Warnings cleanup https://github.com/radare/radare2/issues/1169
- [x] Warnings in sys/mingw64.sh https://github.com/radare/radare2/issues/7226

For example:

```
warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  BOOL ret = VirtualProtectEx (WIN32_PI (process), (LPVOID)(UINT)addr,
```

# Portable Executable and other Windows File Formats

- *For Portable Executable enhancement see [META - Portable Executable](https://github.com/radare/radare2/issues/921)*
- [x] Allow to load .DMP (memory dump of process or kernel) https://github.com/radare/radare2/issues/2598 see [(Lot of work already done in r2-extras)](https://github.com/radare/radare2-extras/blob/master/libr/bin/p/bin_mdmp.c)

# Debugging

## Debugger support

- [ ] ~~libr/debug/p/debug_native.c support for the Cygwin https://github.com/radare/radare2/blob/master/libr/debug/p/debug_native.c https://github.com/radare/radare2/issues/2577~~
- [ ] ~~gdb:// protocol support on Cygwin and Mingw32~~
- [x] Improve debugging of DLL
- [x] Preloading support https://github.com/radare/radare2/issues/2208
- [x] WinDbg protocol support https://github.com/radare/radare2/issues/1246
- [x] WinDbg and PDB loading/connecting on Windows platform
- [x] Native debugging
    - [x] threads support

## Debugger Information

- [ ] Allow to load DWARF (for minw32 applications) during Windows debugging
- [x] Allow to load PDB
- [x] Support of the autoloading needed PDBs for the imported dlls https://github.com/radare/radare2/issues/3128
- [x] PDB symbols support https://github.com/inisider/radare2/tree/pdb_parser

# Other enhancement

- [ ] Add support for [Windows Syscall Table](https://github.com/tinysec/windows-syscall-table)
- [x] Add support for lang/p/pipe.c https://github.com/radare/radare2/issues/2209

# Types

- [x] Add of the all standard windows C types https://github.com/radare/radare2/issues/3654 https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751%28v=vs.85%29.aspx
- [x] Use of the all standard windows C types https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751%28v=vs.85%29.aspx

**Comment by XVilka** [comment]
calling sdb from libr/syscall/d/Makefile should have support for the windows pathnames:
https://github.com/radare/radare2/blob/master/libr/syscall/d/Makefile#L27

**Comment by XVilka** [comment]
One more note, on Cygwin on searching strings r2 returns this error:
```
[0x100401000]> izz
r_sys_cmd_str: not yet implemented for this platform
```

**Comment by crowell** [comment]
@XVilka cygwin can use things like dup2, pipe, etc. 

```diff
diff --git a/libr/util/sys.c b/libr/util/sys.c
index 0e5690c..6f7f413 100644
--- a/libr/util/sys.c
+++ b/libr/util/sys.c
@@ -296,7 +296,7 @@ R_API int r_sys_chdir(const char *s) {
        return r_sandbox_chdir (s)==0;
 }
 
-#if __UNIX__
+#if __UNIX__ || __CYGWIN__
 R_API int r_sys_cmd_str_full(const char *cmd, const char *input, char **output, int *len, char **sterr) {
        char buffer[1024], *outputptr = NULL;
        char *inputptr = (char *)input;
```

should be enough

**Comment by XVilka** [comment]
@crowell push it please, it works.

**Comment by crowell** [comment]
pushed

**Comment by beebob23c** [comment]
re XVilka's comment, in non-cygwin Windows the full strings list from "izz" doesn't succeed either, with a different error

```
[0x00000000]> izz
r_core: Cannot open file ''my.bin''
```
When running on Windows, whether I open a flat binary file or a well-formed PE file, "izz" always says cannot open the file.

"iz" does work on well-formed PE files though

**Comment by radare** [comment]
Remove the quotes. How did u launched r2? Which version of r2 are you using?

**Comment by XVilka** [comment]
@beebob23c please open the separate bug + write a testcase, this is a tracker only, i'll add it into the list.

**Comment by XVilka** [comment]
Note for myself: setup MSYS2 build on AppVeyor also.

**Comment by Manouchehri** [comment]
Not sure if this is helpful or not, but Microsoft is taking questions on PDB if you have any.

https://github.com/Microsoft/microsoft-pdb

**Comment by MariasStory** [comment]
What about the memory dump of process?
I could'n event get strings out :-(.
Please help.

**Comment by XVilka** [comment]
It's already in radare2-extras. Doesn't work though, so should be fixed

**Comment by wargio** [comment]
@XVilka -> Building in MSYS2/Mingw-w64
i build r2 on windows with MSYS2 and Mingw-w64

**Comment by akorchemniy** [comment]
The radare2 book [https://radare.gitbooks.io/radare2book/content/introduction/windows_compilation.html] suggests compiling on Cygwin by running "sys/mingw32.sh". However, I get 

buffer.c
CC cdb_make.c
CC ls.c
CC sdbht.c
In file included from /usr/lib/gcc/x86_64-w64-mingw32/5.4.0/include/stddef.h:1:0,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/_cygwin.h:14,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/_mingw.h:17,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:10,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/stdio.h:9,
                 from cdb.c:3:
/usr/x86_64-w64-mingw32/sys-root/mingw/include/stddef.h:18:11: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘extern’
   _CRTIMP extern int *__cdecl _errno(void);
....
/usr/x86_64-w64-mingw32/sys-root/mingw/include/stdio.h:870:26: error: expected ‘,’ or ‘;’ before ‘_ungetwc_nolock

**Comment by XVilka** [comment]
@akorchemniy sorry, it's completely unrelated to Cygwin builds, moved it into Mingw32 section. Thanks for catching it up!

**Comment by XVilka** [comment]
For creating symlinks in Windows - we can use something like this https://github.com/ocaml/opam/commit/8c74bfb620709d3150ca9ac723465c3a708ed7d9

**Comment by XVilka** [comment]
@a1ext please add what is missing for Windows

**Comment by a1ext** [comment]
> @a1ext please add what is missing for Windows

From what I know, there are the only problem:
- Unicode compatibility got broken

**Comment by XVilka** [comment]
@GustavoLCR @pelijah FYI

**Comment by XVilka** [comment]
I am closing this one then, since most of it fixed, will open the separate issues for what remains.
