### ISSUE TITLE
[TRACKER] Radare2 is not as cool as x64dbg

### ISSUE THREAD

**Issue by jvoisin** [radare/radare2#1206]
![screenshot](http://x64dbg.com/img/slide4.png)
- [x] Show where registers are currently pointing
- [x] Print upward and downward jumps in a different colour #1328
- [x] Anti-antidebug plugins/features #5306
- [x] Thread view
- [x] Find patterns in memory
- [x] Hex-editor https://github.com/radare/radare2/issues/1207
- [x] Patching support
- [x] Assembler
- [x] A neat website
- [x] FLIRT-like technology https://github.com/radare/radare2/issues/2766

**Comment by jvoisin** [comment]
Nah, the *showing reg values* is simply taking the current values of the registers in debug mode, no need for fancy analysis.

**Comment by Maijin** [comment]
@jvoisin I see only remaining issue unchecked is `Print upward and downward jumps in a different colour` correct ?

**Comment by jvoisin** [comment]
Yes sir

**Comment by Maijin** [comment]
Ok then can you remove all the other message of the thread and add a screenshot of this ?

**Comment by radare** [comment]
upward lines are now differently printed

**Comment by radare** [comment]
(not with colors, but meh)

**Comment by Maijin** [comment]
Better with colorzzzzz @jvoisin @XVilka

**Comment by radare** [comment]
done!
