### ISSUE TITLE
[TRACKER] HEX editor mode improvements

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#1207]
- [ ] Nested block highlighting
- [ ] Unify colouring with the other modes of r2
- [x] Ability to change number of columns
- [ ] Apply cparse templates on the hex visual output (need more thinking)
- [ ] Apply **pf** templates on the hex visual output

**Comment by radare** [comment]
can we close this now? i think the only thing thats missing is something that can be enhanced and can be described in a better way

**Comment by XVilka** [comment]
Yes, can be closed.
