### ISSUE TITLE
0.9.9 release

### ISSUE THREAD

**Issue by radare** [radare/radare2#1661]
* [x] Fix IO issue #1959 
* [x] Fix code analysis (regress and find buggy commits)
* [x] PDB with support for pf and td
* [x] Yara3 support (and yara2 at the same time)
* [x] Enforce testsuite (every commit must pass the testsuite)
* [x] ihex:// bug https://github.com/radare/radare2/issues/1843
* [x] fix any errors on building r2-bindings against radare2 (python, nodejs, ducktape)
* [x] documentation how to build radare2-extras for all major platforms
* [x] ELF parse symbols from phdr https://github.com/radare/radare2/issues/1627

Related issues:

r2-0.9.9 missing stuff
======================
Quick stuff to fix
------------------
* [x] afc/afC -> https://github.com/radare/radare2/issues/1514
* [x] af*/afj -> https://github.com/radare/radare2/issues/1545
* [x] Rename ac into aac https://github.com/radare/radare2/issues/2203
* [x] Remove http.public https://github.com/radare/radare2/issues/2152
* [x] syscall->interrupt https://github.com/radare/radare2/issues/2181
* [x] Fix all those cmdline zlul crashes https://github.com/radare/radare2/issues/2220
* [x] Finally define and merge this json radiff https://github.com/radare/radare2/pull/2204
* [x] r2pipe.js must support rlangpipe  https://github.com/radare/radare2/issues/2202
* [x] Kill uppercase tms320 https://github.com/radare/radare2/issues/2192
* [x] Local/args in order https://github.com/radare/radare2/issues/2188
* [x] Fix Yara3 plugin building http://ci.rada.re/view/Bindings/job/radare2-yara https://github.com/radare/radare2-extras/blob/master/yara/yara3

Future
======
* [x] main on mips noot detected https://github.com/radare/radare2/issues/2074
* [x] main detection on PIE  https://github.com/radare/radare2/issues/1813

**Comment by krytarowski** [comment]
Please ping me when you will be in preparation of releasing the next version. I would like to recheck the NetBSD compatibility.

**Comment by krytarowski** [comment]
Downstream request: for the release please set requirement for the minimal/certain version (not git snapshot) of capstone.

The pkgsrc packages releases capstone independently as devel/capstone, which in turn is reused by devel/radare2. The same applies for libzip.

**Comment by radare** [comment]
Try with this tarball: `http://lolcathost.org/b/radare2-0.9.9-git.tar.xz`

if you want to create a tarball for testing for packaging, just use "./configure;make dist"

**Comment by radare** [comment]
release will happen soon. as soon as we get all of most of the bugs
listed in this issue ready. this week i'll try to focus on squash as
much of them as possible. everyone is welcome to help on this :)

**Comment by krytarowski** [comment]
Thank you.
I'm using the latest git snapshots (taken from HEAD) http://pkgsrc.se/wip/radare2-git This package follows the development of radare2 upstream. Currently there are problems to test with too old capstone (the latest stable release). Probably I should create a similar package for capstone to follow upstream.

I know that there is effort to setup CI, I'm open to help you to configure pkgsrc builds (i.e. provide scripts).

**Comment by radare** [comment]
Use make dist for testing. Is not the same as github tarballs. Which is the problem u are having with old capstone.

Making pkgsrc for which platforms? We use a linux box. And i guess u want netbsd .. So we cant crosscompile. I was a pkgsrc maintainer some years ago.. So i know how it works.

**Comment by krytarowski** [comment]
I will stay with tracking the git releases. Testing involves interoperability with packaged separately capstone.

I can help to setup it for Linux.

**Comment by radare** [comment]
Typing make dist from the repo is the correct way to test a release tarball from git.

But iirc only diff should be the inclusion of the capstone srcdir

**Comment by krytarowski** [comment]
Finally I decided to not maintain two packages (release and current) - too little time to follow it daily. Just please ping me when there will be freeze to check the compatibility. Thank you!
