### ISSUE TITLE
[TRACKER] radare2 is not as cool as IDApro (Architecture)

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#1868]
# Architecture

## To be done

- [ ]  Cortex-A7
- [ ]  Cortex-A12
- [ ]  [Fujitsu FR (comes with source code)](https://github.com/radare/radare2/issues/671)
- [ ]  H8/300L, H8/300H, H8S/2000, H8S/2600, H8SX (comes with source code) 
- [ ]  Hitachi H8/500(comes with source code)
- [ ]  Hitachi HD 6301, HD 6303, Hitachi HD 64180
- [ ]  INTEL 8085
- [ ]  INTEL 80196 (comes with source code)
- [ ]  INTEL 860XR (comes with source code)
- [ ]  INTEL 960 (comes with source code)
- [ ]  KR1878 (comes with source code)
- [ ]  Mitsubishi MELPS740 or Renesas 740 (comes with source code)
- [ ]  Hitachi/Renesas M16C
- [ ]  MN102 (comes only with source code)
- [ ]  Motorola/Freescale MC680xx, CPU32 (68330), MC6301, MC6303, MC6800, MC6801, MC6803, MC6805, MC6808, HCS08, MC6809, MC6811, M68H12C, ColdFire 
- [ ]  Motorola MC6812/MC68HC12/CPU12
- [ ]  Freescale HCS12, HCS12X (including XGATE coprocessor)
- [ ]  SPU (Synergistic Processing Unit of the Cell BE) (comes with source code)
- [ ]  MSP430X (comes with source code)
- [ ]  Rockwell C39 (comes only with source code)
- [ ]  SAM8 (comes with source code)
- [ ]  SGS Thomson ST-7, and ST-20 (comes with source code) 
- [ ]  TLCS900 (comes only with source code)
- [ ]  unSP from SunPlus
- [ ]  Philips XA series (51XA G3)(comes with source code)
- [ ]  Intel xScale
- [ ]  Zilog Z8, Zilog Z180, Zilog Z380 (comes with source code)
- [ ]  Cortex-A5
- [ ]  Analog Devices AD218x series (ADSP-2181, ADSP-2183,ADSP-2184(L/N), ADSP-2185(L/M/N), ADSP-2186(L/M/N), ADSP-2187(L/N),ADSP-2188M/N, ADSP-2189M/N)
- [ ]  DEC Alpha
- [ ]  DSP563xx, DSP566xx, DSP561XX(comes with source code)
- [ ]  TI TMS320C2X
- [ ]  TMS320C5X
- [ ]  TMS 320C54xx
- [ ]  TI TMS320C27x/TMS320C28x
- [ ]  Hewlett-Packard HP-PA (comes with source code)
- [ ]  TMS320C3
- [ ]  Hitachi/Renesas SuperH series: SH1, SH2, SH3, SH-4A, SH-2A, SH2A-FPU
- [ ]  Book E (Embedded Controller Instructions)
- [ ]  Freescale ISA extentions (isel etc.)
- [ ]  SPE (Signal Processing Engine) instructions
- [ ]  AltiVec (SIMD) instructions
- [ ]  Hypervisor and virtualization instructions
- [ ]  All instructions from the Power ISA 2.06 specification (Vector, Decimal Floating Point, Integer Multiply-Accumulate, VSX etc.)
- [ ]  Cell BE (Broadband Engine) instructions (used in PlayStation 3)
- [ ]  VLE (Variable Length Encoding) compressed instruction set
- [ ]  Xenon (Xbox 360) instructions, including VMX128 extension
- [ ]  Paired Single SIMD instructions (PowerPC 750CL/Gekko/Broadway/Espresso, used in Nintendo Wii and WiiU)
- [ ]  Motorola/Freescale PowerPC-based cores and processors, including (but not limited to): 
- [ ]  MPC5xx series: MPC533/MPC535/MPC555/MPC556/MPC561/MPC562/MPC563/MPC564/MPC566 Note: code compression features of MPC534/MPC564/MPC556/MPC566 (Burst Buffer Controller) are currently not supported
- [ ]  MPC8xx series (PowerQUICC): MPC821/MPC850/MPC860
- [ ]  MPC8xxx series (PowerQUICC II, PowerQUICC II Pro, PowerQUICC III): MPC82xx/MPC83xx/MPC85xx/MPC87xx
- [ ]  MPC5xxx series (Qorivva): MPC55xx, MPC56xx, MPC57xx
- [ ]  QorIQ series: P1, P2, P3, P4, P5 and T1, T2, T4 families
- [ ]  Intel IA-64 Architecture - Itanium.
- [ ]  Motorola DSP 56K
- [ ]  Motorola MC6816
- [ ]  MIPS Mark I (R2000)
- [ ]  MIPS Mark II (R3000)
- [ ]  MIPS Mark III: (R4000, R4200, R4300, R4400, and R4600)
- [ ]  MIPS Mark IV: R8000, R10000, R5900 (Playstation 2)
- [ ]  Allegrex CPU (Playstation Portable), including VFPU instructions
- [ ]  Cavium Octeon ISA extensions
- [ ]  MIPS16 (MIPS16e) Application Specific Extension
- [ ]  MIPS-MT, MIPS-3D, smartMIPS Application Specific Extensions
- [ ]  Tohiba TX19/TX19A Family Application Specific Extension (MIPS16e+ aka MIPS16e-TX)
- [ ]  Mitsubishi M32R(comes with source code)
- [ ]  Mitsubishi M7700 (comes with source code)
- [ ]  Mitsubishi M7900 (comes with source code)
- [ ]  Nec 78K0 and Nec 78K0S (comes with source code)
- [ ]  STMicroelectronics ST9+, ST-10 (comes with source code)
- [ ]  Siemens C166 (flow) 
- [ ]  Fujitsu F2MC-16L, Fujitsu F2MC-LC(comes with source code)

## Done

- [x]  AMD K6-2 3D-Now! extensions
- [x]  ARM Architecture versions from v3 to v8 including Thumb, Thumb-2, DSP instructions and NEON Advanced SIMD instructions.
- [x]  ARMv4/ARMv4T: ARM7 cores (ARM7TDMI/ARM710T/ARM720T/ARM740T), ARM9 cores (ARM9TDMI/ARM920T/ARM922T/ARM940T)
- [x]  ARMv5/ARMv5TE/ARMv5TEJ: ARM9 cores (ARM946E-S/ARM966E-S/ARM968E-S/ARM926EJ-S/ARM996HS), ARM10E (ARM1020E/ARM1022E/ARM1026EJ-S)
- [x]  ARMv6/ARMv6T2/ARMv6Z/ARMv6K: ARM11 cores (ARM1136J(F)-S/ARM1156T2(F)-S/ARM1176JZ(F)-S/ARM11 MPCore)
- [x]  ARMv6-M: Cortex-M0/Cortex-M0+/Cortex-M1 (e.g. NXP LPC800/LPC1xxx, Freescale Kinetis L and M series, STM32 F0 series etc.)
- [x]  ARMv7-M: Cortex-M3 (e.g. NXP LPC17xx/18xx/13xx, STM32 F1/F2/L1 series, TI Stellaris, Toshiba TX03/TMPM3xx etc.)
- [x]  ARMv7E-M: Cortex-M4 (e.g. NXP LPC43xx, STM32 F3/F4series, TI Stellaris LM4F, Freescale Kinetis K series and W series,Atmel AT91SAM4 etc.)
- [x]  ARMv7-R: Cortex-R4(F)/Cortex-R5/Cortex-R7 (e.g. TI TMS570LS etc.)
- [x] Cortex-A5
- [x]  Cortex-A8
- [x]  Cortex-A9
- [x]  Cortex-A15
- [x]  ARMv7 (custom): Apple A4/A5/A5X/A6/A6X (Swift microarchitecture, used in Apple's iPhone/iPod/iPad/AppleTV), Qualcomm Snapdragon Note: this list is incomplete; code for any ARM-compliant core can be disassembled 
- [x]  ATMEL AVR (comes with source code)
- [x]  DEC PDP-11(comes with source code)
- [x]  GameBoy
- [x]  Hitachi/Renesas H8/300
- [x]  INTEL 8080
- [x]  INTEL 8051 (comes with source code)
- [x]  INTEL 80x86 and 80x87
- [x]  INTEL Pentium family, including SSE, SSE2, SSE3, SSE4 
- [x]  Java Virtual Machine (comes with source code)
- [x]  Microsoft .NET (Common Language Infrastructure bytecode)
- [x]  MOS Technologies 6502 (comes with source code) 
- [x]  NSC CR16 (comes only with source code)
- [x]  NEC V850
- [x]  V850E1 (V850ES) (comes with source code)
- [x]  EFI Byte Code (EBC) (comes with source code)
- [x]  MSP430
- [x]  PIC 12XX, PIC 14XX, PIC 18XX, PIC 16XXX (comes with source code) 
- [x]  Z80
- [x]  x64 architecture (Intel x64 and AMD64)
- [x]  ARM64 Architecture (aka AArch64)
- [x]  Cortex-A53
- [x]  Cortex-A57
- [x]  ARMv8 (custom): Apple A7 (Cyclonemicroarchitecture, used in iPhone 5s)
- [x]  Dalvik (Android bytecode, DEX)
- [x]  [TMS320C6X](https://github.com/radare/radare2/issues/1602)
- [x]  [TMS320C64X](https://github.com/radare/radare2/issues/4761)
- [x]  TMS320C55xx
- [x]  Hitachi SH4
- [x]  IBM/Motorola PowerPC/POWER architecture, including Power ISA extensions:
- [x]  Power PC 4xx, 6xx, 74xx, e200 (including e200z0 withVLE), e500 (including e500v1, e500v2 and e500mc), e600, e700, e5500,e6500 cores
- [x]  [Infineon Tricore architecture (up to architecture v1.6)](https://github.com/radare/radare2/issues/670)
- [x]  MIPS 
- [x]  MIPS32
- [x]  MIPS32r2
- [x]  MIPS32r3
- [x]   MIPS64
- [x]  MIPS64r2
- [x]   MIPS64r3
- [x]  SPARCII, ULTRASPARC

---

**Comment by radare** [comment]
the sparc disassembler from capstone lacks lot of instructions, so use gnu until capstone gets updated

**Comment by oddcoder** [comment]
I guess I will start working on the PIC architecture from scratch following the instruction set and registers from microchip Section 29. Instruction Set manual at microchip.com/downloads/en/DeviceDoc/31029a.pdf

**Comment by radare** [comment]
Awesome! 👍

**Comment by oddcoder** [comment]
it is time to put a check near the pic18cxx ?

**Comment by Maijin** [comment]
Already done since a long time :+1:

**Comment by lucasduffey** [comment]
+ hexagon qdsp6

**Comment by Maijin** [comment]
@lucasduffey No, idapro doesn't support hexagon officialy https://www.hex-rays.com/products/ida/processors.shtml Open another issue.

**Comment by Maijin** [comment]
Closing this.

**Comment by devnoname120** [comment]
@Maijin Why?

**Comment by Maijin** [comment]
Doesn't make sense anymore better track needs.

**Comment by trufae** [comment]
Why is this issue closed? I think it can be a nice place to discuss about which archs. about ST-10:

* https://www.st.com/resource/en/datasheet/st10f273m.pdf
* https://www.tasking.com/support/c166-classic/a166_v8.9.pdf
* https://www.tasking.com/support/c166-classic/c166_v8.7.pdf

cannot find any opensource disassembler

**Comment by Maijin** [comment]
We (You and me) decided to close it in profit of individual issues.

And it indeed makes more sense to discuss and post document architectures individually rather than in a big giant issue.

**Comment by radare** [comment]
i dont have the time or the source to implement the support for that architecture, and opening an issue that will be closed at some point makes no sense to me, i just dropped this info in here for the future someone to find the links without having to google
