### ISSUE TITLE
[META] JSONification of the radare2 commands

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2388]
Here to keep track of the status of the JSONification of the radare2 commands and probably unification of the JSON produced.
- [ ] Implement JSON for `dtcj` https://github.com/radare/radare2/issues/1594
- [x] Improvements of `iS`/`iSj` https://github.com/radare/radare2/issues/1289
- [x] Add JSON output to ranal2 https://github.com/radare/radare2/issues/1659
- [x] ESIL structured output + JSON representation https://github.com/radare/radare2/issues/2387
- [ ] REIL JSON representation

FYI
JSON identation is available with ~

```
 |  ~{}   json indentation
 |  ~{}.. less json indentation
```

**Comment by radare** [comment]
REIL JSON: aorj

For the dtcj... well first we need to save the results of dtc somewhere.. and maybe `dtj` would be more useful in most use cases

**Comment by radare** [comment]
imho we can close this as long as dtcj makes no sense because its not buffered and we are adding json as soon as its requested by someone
