### ISSUE TITLE
1.0.0 release

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#2423]
Moved after 0.9.9
* [ ] replace parts of IO layer with siol https://github.com/radare/radare2/issues/2427
* [ ] improve building r2-bindings on Windows (mingw32/cygwin)
* [ ] WinDBG https://github.com/radare/radare2/issues/1246
* [ ] Loading PDB file automatically if present while opening PE file
* [ ] Import the new ELF parser https://github.com/radare/radare2/tree/elf-ng
* [ ] Eliminate GPL (vs LGPL) and GNU code as much as possible (binutils and grub)
* [ ] ranal2 into rasm2 -A https://github.com/radare/radare2/issues/1658 related https://github.com/radare/radare2/issues/1659
* [ ] regex is vulnerable? https://github.com/radare/radare2/issues/2179
* [ ] pd -x noisy and sometimes buggy https://github.com/radare/radare2/issues/2149
* [ ] Obey colors in diffgraphs  https://github.com/radare/radare2/issues/2141
* [ ] Show local var values https://github.com/radare/radare2/issues/1977
* [ ] working decompiler
* [ ] Fix pedantic build http://ci.rada.re/job/radare2-pedantic/1011/
* [ ] Fix clang build http://ci.rada.re/job/radare2-clang/1016/

**Comment by XVilka** [comment]
- [ ] Fix pedantic build http://ci.rada.re/job/radare2-pedantic/1011/
- [ ] Fix clang build http://ci.rada.re/job/radare2-clang/1016/
