### ISSUE TITLE
META - Autocompletion

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#3033]
## Main Fix

- [ ] Move autocompletion tout of libr/core/core.c to the corresponding commands, Right now it's a monstrous function in libr/core/core.c
I think splitting it to the smaller chunks (workers/handlers) and moving those chunks closer to the actual commands implementation will make code maintenance and enhancement tasks easier.

## Commands to be fixed

- [x] autocomplete `mg`
- [x] autocomplete `md`
- [x] autocomplete `afn`
- [x] autocomplete for `k` https://github.com/radare/radare2/issues/853
- [x] autocomplete `e asm.arch=<tab>`
- [x] !!!$eval says (null)
- [x] autocomplete when there's a space between the eval var and the `=` char.
- [x] autocomplete `e cmd.pdc=<tab>`
- [x] autocomplete `e asm.cpu=<tab>`
- [x] autocomplete `e asm.os=<tab>`
- [x] autocomplete `e anal.arch=<tab>`
- [x] autocomplete for `S-` with section name
- [x] autocomplete for `#![lang] [file]`
- [x] autocomplete for all `t` commands
- [x] autocomplete the typenames in 'tl' commands
- [x] autocomplete for element in `pf` : pf.elf_header <- ok ; pf.elf_header.<tab> <- not ok

**Comment by radare** [comment]
to autocompletion fixed

**Comment by Maijin** [comment]
related to some other issues added

**Comment by Maijin** [comment]
What about this for 0.10.0 ?

**Comment by jvoisin** [comment]
It would be super-awesomely-nice!

**Comment by radare** [comment]
And super-easy-to-do, but im too lazy to do it now, anyone? otherwise i'll try to find some time for it next week.

**Comment by alvarofe** [comment]
easy for @radare or easy for everyone :P?. I'll look at it if this is important for the release

**Comment by radare** [comment]
Imho the most important autocompletion pending is for pf

**Comment by Maijin** [comment]
imho k and pf are the most important cause unusable without autocompletion

**Comment by radare** [comment]
Agree.

**Comment by radare** [comment]
If i find some time i'll be doing the 'k' autocompletion, i've moved the issue to 1.0 as long as current state is quite good, and we need some stabilization time window.

**Comment by XVilka** [comment]
Added item for the `#!pipe [lang] [file]` autocompletion request.

**Comment by radare** [comment]
+1

**Comment by Maijin** [comment]
@oddcoder don't forget about this too.

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/issues/708

**Comment by radare** [comment]
pfj and other pf subcommand autocompletion should work fine, can you confirm?

**Comment by Maijin** [comment]
No they don't, look at the issue:

![image](https://cloud.githubusercontent.com/assets/1408600/19769886/76a3f702-9c5d-11e6-8bd8-4d5b7b22ba66.png)

**Comment by radare** [comment]
autocompleting Sr and S- makes no sense

**Comment by Maijin** [comment]
? Why ?

**Comment by Maijin** [comment]
It totally makes sense...

**Comment by XVilka** [comment]
@MaskRay may be this can be of your interest

**Comment by MaskRay** [comment]
I use sth like 

```
// A: address
// i: int
// l: non-negative int64 for length
// F: filename
// s: non-empty string
// R: register
```

and use `DEFINE_CMD_F(core, f+, "s?lA");` to define a command.

`s` for non-empty string
`?` marks the start of optional arguments
..
..

for argument type specifiers in my rewrite.

```c++
class Context {
public:
  union Argument {
    Addr addr_val;
    int int_val;
    i64 i64_val;
    u64 u64_val;
  };
  std::vector<std::string> args_;
  std::vector<Argument> vals_;

  Addr addr_arg(int i) const { return vals_[i].addr_val; }
  Addr addr_arg_def(int i, Addr def) const { return i < nargs() ? vals_[i].addr_val : def; }
  int int_arg(int i) const { return vals_[i].int_val; }
  int int_arg_def(int i, int def) const { return i < nargs() ? vals_[i].int_val : def; }
  i64 i64_arg(int i) const { return vals_[i].i64_val; }
  i64 i64_arg_def(int i, i64 def) const { return i < nargs() ? vals_[i].i64_val : def; }
  u64 u64_arg(int i) const { return vals_[i].u64_val; }
  u64 u64_arg_def(int i, u64 def) const { return i < nargs() ? vals_[i].u64_val : def; }
  std::string str_arg(int i) const { return args_[i]; }
  std::string str_arg_def(int i, std::string&& str) const { return i < nargs() ? args_[i] : str; }
  int nargs() const { return int(args_.size()); }
};

Error cmd_flag(RCore* core, string_view cmd, const Context& ctx) {
  ...
  switch (cmd[0]) {  //   // undefined behavior, i have not changed this
  case '\0':
    if (! ctx.nargs()) {
      dfs_list_flags(cons, root_flag_space, "");
    } else {
      name = ctx.str_arg(0);
      if (! resolve_flag(name, &parts))
        return Error::kInvalidArgument0;
      for (size_t i = 0; i < parts.size() - 1; i++)
        if (! (space = space->get_space(parts[i])))
          return err_not_found(name);
      if (! (flag = space->get_flag(name)))
        return err_not_found(name);
      cons->printf("0x%08" PRIx64" %" PRIu64" %s\n", flag->left(), flag->len_, flag->name_.c_str());
    }
    break;
```

**Comment by radare** [comment]
i have upudated the list of missing <tab> handlers

**Comment by XVilka** [comment]
@deepakchethan can you please take a look also for autocompleting:
- `e asm.cpu=` - see the example how it is done with `e asm.arch=`
- `k` commands, it is a custom autocompletion as well, like in offsets in visual mode, or `ms` command.

**Comment by radare** [comment]
related https://github.com/radare/radare2/issues/8806

**Comment by radare** [comment]
related feb65fdac3931133560261acd04d22758cf05850

**Comment by radare** [comment]
@wargio @deepakchethan remaining autocompletions are for md/mg (which there's a similar issue that you have been working on (https://github.com/radare/radare2/pull/14284) and `k` which is low prio for this release. so im moving that for 3.7

**Comment by deepakchethan** [comment]
Will start working on autocompleting the command k

**Comment by deepakchethan** [comment]
> @deepakchethan can you please take a look also for autocompleting:
> 
>     * `e asm.cpu=` - see the example how it is done with `e asm.arch=`
> 
>     * `k` commands, it is a custom autocompletion as well, like in offsets in visual mode, or `ms` command.

Autocompletion for `asm.cpu` is already implemented but it is dependant on `asm.arch` on choosing certain architectures the autocompletion options will be visible. Please let me know if all the cpus must be shown.

**Comment by radare** [comment]
yeah i think we can close this issue finally :)
