### ISSUE TITLE
META - Class (C++, ObjC, Java, Swift, etc) parsing support

### ISSUE THREAD

**Issue by radare** [radare/radare2#3064]
- [x] Native ObjC support
- [x] Use standard indentation rules as suggested in doc/syntax.md
- [x] Fix `rabin2 -rc` (methods doesnt show address wtf)
- [x] objc class fields are marked as methods, must be fixed
- [x] Support objc-generics information
- [x] Method names shouldnt contain the classname. But maybe it's useful for grep to show the classname separated by a space instead of ::
- [x] Confirm/enhace automatic class extraction information works
  - [x] Dalvik
  - [x] C++
  - [x] Swift
  - [x] Java
- [x] Add bin.classes eval var to toggle loading class information from bin or not (like bin.strings do, but for classes)
- [ ] C++ class reconstruction from code analysis
- [x] Write Test cases
- [x] Visual mode to introspect classes, methods and fields

**Comment by radare** [comment]
No generics info found in binary form, nothing to see here. keep walking

**Comment by radare** [comment]
For swift https://github.com/neonichu/swift-dump which uses a similar method i do in rabin2 . demangle c++ names and parse by ::. just test and confirm

**Comment by radare** [comment]
i'll do the VB to walk over the rbin info in visual mode

**Comment by radare** [comment]
we just need tests to close this issue. pls @Maijin can u test that ic works on swift, java and c++ without having class information? (using symbol names)

**Comment by radare** [comment]
@Maijin can u pls write some tests for swift-main and swift-main2? i want to be sure that the behaviour in `ic` doesnt changes.. even if its not "perfect" yet

**Comment by radare** [comment]
For Swift has been implemented in fb47d2ce74f6c1d9c91f1cb8bb9bb97b50047794, but this should be generalized even more to support other languages. testing is welcome

**Comment by radare** [comment]
seems to be broken for Java

**Comment by radare** [comment]
cc @h4ng3r

**Comment by radare** [comment]
i think we can close this now that java is done. the c++ analysis class extraction can be a separate issue.
