### ISSUE TITLE
META - Add function argument detection

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#3655]
![image](https://cloud.githubusercontent.com/assets/1408600/13150924/14752dfa-d668-11e5-869f-32d10f3a8b4a.png)
- [x] Add precompiled headers in sdb file for windows OS #3654 
- [x] Autoload those types when `e asm.os = windows`
- [x] Add "return type" in the Functions definition files #1953
- [x] Use Native types instead of pf types in Functions definition files
- [x] What about `const char *local` for example what should I put in the database for the name of type since it's composed of 2 words instead of just one like `HINSTANCE` ?
- [x] Enhance current display (maybe reuse the `e asm.calls` display?)
- [x] What about adding default `aeim` when `e asm.emuwrite` is used ?
  `Maijin: This is done by afta somehow, could be enhance but let's check it.`
- [x] What in the case of autorename stuff like `sub.strrchr_8f0` what to put in the database `sub.strrchr_*` ?
- [x] Changing easily the call convention
- [x] Add support for linux-x86-32 functions since some of them have already been added => https://github.com/radare/radare2/blob/master/libr/anal/d/linux-x86-32
- [x] Add support for linux-x64 functions 32/64
- [x] Add support for osx functions 32/64
- [x] Add support for naming local variables based off esp #3735
- [x] Merge with no-return (an?)  #5772
- [x] Add afta by default on aaa and aaaa
- [x] Documenting types key=value Sdb
- [x] Merge asm.emu and asm.emuwrite into the new implementation #5759
- [x] Improve code coverage for `aftm` probably with symbolic execution
- [ ] Add Autocomplete for all new commands #3033 
- [ ] Ability to load/export IDA TIL Files
- [x] Add display stack frame of a function

**Comment by Maijin** [comment]
Something like this? 
* If the e asm.os = windows/linux/... It loads the predefined set of types for the platform
* It loads the definition something containing return type and native types(not pf) : sym.imp.user32.dll_LoadIconA=HINSTANCE:hInstance LPCTSTR:lpIconName ; HICON
* Display LoadIconA(HINSTANCE:0x1000,LPCTSTR:0x10000) [return HICON]

ping  @radare

**Comment by Maijin** [comment]
Usage of pf in the function definition is wrong.
1) Almost no user will contribute because don't know pf, which is highly probable
2) Types<->pf are already implemented see [here](https://github.com/radare/radare2/blob/master/libr/anal/d/windows-types) , that will means potentially 2 database for the same info (with wrong stuff potentially) 
3) If there is an error due to a wrong types<->pf in a function definition file, that will means we'll have to remove the errors for all function using this wrong conversion instead of just changing the types in the sdb types file.

**Comment by XVilka** [comment]
![fun_args](https://cloud.githubusercontent.com/assets/203261/13172747/c4709396-d70a-11e5-9ecb-beb03a8844eb.png)

**Comment by dukebarman** [comment]
:+1:

**Comment by radare** [comment]
this is already done. but doesnt works in all cases because if the arguments are passed in registers there’s no direct way to catch this. but args are detected in the same way as the local vars.

**Comment by radare** [comment]
maybe we can update this issue @oddcoder

**Comment by oddcoder** [comment]
I am updating it regularly (checking the done parts)

**Comment by Maijin** [comment]
For 1.0.0 objectives for this issue would be to merge asm.emu, asm.emuwrite databases that;s really important to avoid shipping duplicates, Add Autocomplete for all new commands #3033 and Add afta by default on aaa and/or aaaa

**Comment by radare** [comment]
Emuwrite is dangerous and irreversible. I  would not merge it

**Comment by radare** [comment]
Ok for the autocompletion, go for it if you find any

**Comment by Maijin** [comment]
@radare I'm speaking about the databases, What's the point of keeping two databases that are doing exactly the same ????

**Comment by Maijin** [comment]
For autocompletion it's all t commands

**Comment by Maijin** [comment]
https://github.com/radare/radare2/issues/5759 here

**Comment by radare** [comment]
@oddcoder can u have a look atthis? Also, i think all this stuff should be distributed in .h form and precompiled to key=value sdb database later instead of providing hand made stuff

**Comment by radare** [comment]
Agree

**Comment by radare** [comment]
Dont mix issues

**Comment by Maijin** [comment]
yes but as said for distributing .h tcc must work correct and it doesn't there is an hackmd.io with the issues related to tcc impacting this opened

**Comment by oddcoder** [comment]
yess tcc is complex big task on its own, for merging all databases I am allocating time to work on

**Comment by radare** [comment]
tcc was working fine when i was using it and i see not much complexity on it… where’s the link to that issue?

**Comment by Maijin** [comment]
Here again https://hackmd.io/OwNmE5gEwZhhaAjAMwAzPgFgKYGMPgwjjzC5TjJSrQBG2ATEA===

**Comment by Maijin** [comment]
@radare Idea for merging those database and the function emulation functionnality is also the next step on the initial GSOC project:

![image](https://cloud.githubusercontent.com/assets/1408600/18968349/e1305416-8688-11e6-88be-edfd3e252065.png)

**Comment by XVilka** [comment]
What about closing this one and opening a new one?

**Comment by radare** [comment]
Ok

**Comment by Maijin** [comment]
I will do that later yes

**Comment by oddcoder** [comment]
we just need a new one for TIL files ... everything else is finished if \o/ (except autocompletion)

**Comment by Maijin** [comment]
No, not everything is fixed, but the issues have been splitted. I will recreate a META later.
