### ISSUE TITLE
[META] Heap explorer/analysis

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#5390]
- [x] Linux glibc https://github.com/radare/radare2/pull/5335
 - [ ] Windows https://github.com/radare/radare2/issues/4318
 - [ ] OS X - see https://github.com/blankwall/MacHeap for ideas/examples
 - [ ] whatever

**Comment by XVilka** [comment]
See also https://github.com/cloudburst/libheap

**Comment by XVilka** [comment]
FYI @n4x0r , @javierprtd . @soez

**Comment by n4x0r** [comment]
currently dmh supports almost all the features that libheap gdb plugin does. we still have to work on concurrent heap support but i believe that is about it.

**Comment by XVilka** [comment]
For jmalloc - this one is interesting https://github.com/CENSUS/shadow

**Comment by XVilka** [comment]
@devnexen I see you are lately working on OpenBSD support - you might want to check this one too.

**Comment by XVilka** [comment]
@morbith-dqtz Saw your PR recently, you might want to check also this one

**Comment by XVilka** [comment]
Google open sourced their tcmalloc recently - https://github.com/google/tcmalloc
