### ISSUE TITLE
General todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5493]
- [ ] libr/debug/p/drx.c <- not used .. debug must have a hw reg api for drx and gpio
- [x] ah -> add hint to define calls that do not return
- [ ] rabin2 -x should not work on non-fatmach0 files
- [x] foldable stuff .. was in r1..redo?
- [ ] cmp rip+xx -> not resolved wtf
- [ ] search for CALL instructions in text segment.
  - analyze the destination address of each call destination
- [ ] integrate dwarf parser with disassembler and debugger
- [ ] step back .. log all state changes on every debugger stop
- [ ] timeout for code analysis (check timestamp)
- [ ] add analysis points continuation, so 'aa' can be used progressively
- [ ] Allow to seek to branch N like in visual, but from cmdline
- [ ] refactor vmenus.c -> refresh function must be redefined for each menu
- [ ] show hints for
    0x100005eca     ff2540130000     jmp qword [rip+0x1340] [1]             
- [ ] Implement debugger backtrace properly
- [ ] crackme mach0 happy with rbin
- [ ] if no debugger supported, say so... r_io must ?
- [ ] check search multiple keywords and signatures
- [ ] search for antidebug/disasm tricks opcodes
  - allows to find interesting points to analyze
- [ ] use slices for r_list_iter primitives

As per #5424.

(Note: I accidentally bumped the enter key so the original title for this thread was garbage).

**Comment by DanTheColoradan** [comment]
Dang it. Sorry.

**Comment by DanTheColoradan** [comment]
I noticed someone checked off two items here. Can I start making a new issue for the rest? I'll just make the title of each one the same as the checklist item and leave it either empty or if it has info I'll put that in the description.

**Comment by Maijin** [comment]
could be cool if @radare could also check the stuff so we can get rid of the most of stuff prior flooding github even more...

**Comment by DanTheColoradan** [comment]
I think maintainers can? So yeah... Would like that.
