### ISSUE TITLE
Bugs todo migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5494]
- [ ] RBinCreate:
  - mach0 create for darwin-ppc
  - mz
  - pe64
  - plan9 bins
- [x] Implement support for args in 'oo' (like in r1s !load debugger..)
- [ ] opening a file from inside r2 doesnt clears internal data (strings..)
- [x] backtrace for linux or osx at least
- [x] implement 'ax' to get/set xrefs (better than afl <addr>) .. or afx?
- [ ] shell encoder - get x86-64 one from twitter
  - http://funoverip.net/2011/09/simple-shellcode-obfuscation/
  - shellforge.. and review current shellcodes :?
- [ ] rasm2 must support binary creation help message or so..
  - rabin2 integration must be easier
- [ ] Add support for classes in c++, objc, java, swift binaries
  - command to add new classes
- [ ] Tracing support for the debugger
  - "e cmd.trace=dr=;.dr*;pd 2@eip"
  - dca sym.main imp.printf
  - dbc
- [ ] fix for indirect list manipulations -- looks like a similar problem with r_cons recusivity
  - when you are iterating a list you CANT remove items from it
  - this is..you CANT call r_core_cmd() while iterating flags unless you want to crash
  - we probably need to queue the deletions and use a commit-like methodology
  - this way we avoid duplications
```
 RListBox *b = r_flag_get_list ();
  r_list_foreach (b, iter, item) {
    r_list_delete_iter_later (b, iter);
  }
  r_list_commit (b);
```
  - [ ] Add r_cons_prompt () ... calling set_prompt + fgets -- this api needs cleanup
    - set prompt, set line, fgets
    - strict width in visual

As per #5424.
