### ISSUE TITLE
Nibble todo migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5495]
- [ ] Analyze this opcode: ff2518130000     jmp qword [rip+0x1318]
- [ ] Support for proper analyze of TinyPE binaries
- [ ] Do not show XREF info if in the same function?
- [ ] r_anal
  - Code analysis (detect when an argument is a flagmask or enum and display text format) (ollydbg)
- [ ] r_bin
  - PE: native subsystem? http://radare.org/get/w32/mrxnet.tgz
- [ ] Fix RAnalCond
- [ ] code analysis must resolve jump tables
- [ ] allow to hook r_asm_disassemble and assemble with custom callbacks
  - extend a disassembler with own instructions.
- [ ] For each "call" or "push offset"+"ret" create a function.
  - And, if deep code analysis is enabled:
  - Search every possible function by searching typical prologs and put them in a queue.
  - Perform the same actions as in the previous steps with the entry points.
- [ ] detect strings in code analysis
- [ ] register renaming (per-instruction or ranges)
  - r_parser fun? a specific asm.parser plugin that does all this tricks?
- [ ] Display getsym() stuff in rabin2, not only legit syms
- [ ] dmi command must read from memory if no file path provided
  - rabin from memory ftw, to get libnames of dll, so..
- [ ] add support for sign/unsigned registers..or at least a way to cast them
- [ ] use r_anal_value everywhere
- [ ] diff code analysis
  - diff two programs
     - 1st level:
        - check all functions EQUAL, DIFFERENT, REMOVED, ADDED
        - check all symbols
        - check all imports
        - check all strings
     - 2nd level:
        - basic block level diffing (output in graph mode)

As per #5424.

**Comment by radare** [comment]
Dont do that. Issues must be unitary and atomic. A single issue cant hold over 9000 different unrelated issues. Otherwise managing them with milestones and assigning to people makes no sense.
