### ISSUE TITLE
Binaries todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5499]
- [ ] add support for .a files (r_fs supports cpio and ar archives...)
- [ ] add support for .rar files
- [ ] Implement rap:// upload/download protocol commands (maybe just system() with rsc2+wget?
- [ ] Reimplement or fix the delta diffing in C - first we need to do it for ired..
- [ ] Ranged/scrollable zoom mode
- [ ] Add support for STATIC_PLUGINS in r_lang
  - r_lang_define is implemented in lang.c, but requires the collaboration
    of the plugins to properly setup the environment for the script execution.
  - Add support for STATIC_PLUGINS in r_lang
  - dlerror(/usr/lib/radare2/lang_perl.so): libperl.so: cannot open shared object file: No such file or directory
    This issue is fixed by setting LD_LIBRARY_PATH...looks like dlopen ignores rpath
- [ ] gdiff
  - graph based fingerprints? (cyclomatic complexity...)
- [ ] rcore
  - do not allow to disassemble unaligned addresses (toggle)
  - r_asm can reduce cpu without disasm on fixed size ops archs.
- [ ] Add support for templates -- like in 010
  http://www.sweetscape.com/010editor/templates.html
- [ ] templates #!template peheader.template
  - pT template.foo #   r_print_template
  translate into c code and gets compiled. use rcc+rasm?
  it is like a extended regular expression engine

As per #5424.
