### ISSUE TITLE
Debugger todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5500]
- [ ] Skip instruction
- [ ] Step until end of frame (stack pointer restored) (store sp, check if nsp>sp)
- [ ] stepover waits for one unknown event that cannot be stopped
- [ ] code injection facilities? (wtf? insert, execute, restore)
- [ ] Trace contents of buffers: filter search results..?  cc 8080 @@ hit* .. check for values that has changed.
- [ ] Record trace of register status for each function when running
  - r_reg_arena_copy();
- [ ] Implement list threads on ALL supported platforms (win,lin,osx)
- [ ] All threads must be stopped when a breakpoint is handled..
- [ ] Add support for windbg+virtualkd
- [ ] Floating point registers
- [ ] MMX/XMM/DRX control
- [ ] Implement dump+restore as macros (dump,)
- [ ] Implement software stepping (with code analysis+breakpoints)
- [ ] Implement dbg.bep - in r_core? in r_debug after attach? maybe only in r2 binr?
  - must be refined.. and look for better names

As per #5424.
