### ISSUE TITLE
Pancake todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5501]
- [ ] Implement PTRACE_BLOCK on Linux
- [ ] fork/clone child . inject code to create new threads or pids
- [ ] Functions in r_util to get lil/big ut8,16,32 from ut8*
  - already done..must find better names probably
- [ ] Implement RAnalCall (analyze function arguments, return values, propagate types..)
  - define number of arguments for given function
  - warn if signature and analysis differs in number of args or so..
  - when calling a function
    - identify arguments passed and compare with arguments required
    - if they do not match: we need to warn/ask user/store multiple options
       - function signature comparsion if they dont match
       r_anal_fcn_cmp (anal, f1, f2);

As per #5424.
