### ISSUE TITLE
To think about todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5503]
- [ ] Ranged value:
  - ut64 from, to
  - restrict : %2 (module)
- [ ] Add support for aout binaries?
- [ ] eprintf should be modified to log into a file
  - eprintf_open() -- start log to file
  - eprintf_close() -- stop log to file
- [ ] Only use uppercase KMG for Kilo,Mega,Giga in r_num? - 'g' is for double
- [ ] radare2.c:217 . find name for maxfilesize to hash
- [ ] r_list_foreach_prev is buggy, review and remove..
- [ ] make symstall in r2-bindings/ ?
- [ ] Add deltified offset in PC? +10, +30 ... asm.reladdr
- [ ] regio not implemented // it is really necessary? imho no..
- [ ] distribute 'spp' with 'rarc2' ? imho no
- [ ] Add graph.nodecolor graph.bgcolor graph.edgecolor ??

As per #5424.
