### ISSUE TITLE
Refactoring todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5504]
- [ ] Rename r_hashtable -> r_ht
- [ ] Review the r_flags api
- [ ] Add pipe_to_buffer..not only file descriptors
- [ ] r_config set_int and so..simplify
  - find/use more common cases for char* or &int maps
    - automatic callbacks for most common usecases
- [ ] Merge r_socket inside r_util ?
- [ ] Is RCore->block and blocksize a RBuf ? refactor!11
- [ ] Discuss missing r_core_sysenv_update in core/file.c:33
- [ ] Add RLog API.. pipeable to disk and stderr..also hookable ..cool for ui (partially done)
- [ ] Redesign core/disasm.c to provide a pluggable api
- [ ] Move 'r_syscall_t' stuff into r_debug (sync r_core)
- [ ] Implement r_bind api to link multiple pointers
  core->asm = r_bind_set (core->asm->bind, r_asm_new ());
- [ ] Find a better name for r_buf_fread (really?)

As per #5424.
