### ISSUE TITLE
To wipe todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5505]
- [ ] Move manpages from man/ to binr/*/? (harder to maintain?)
- [ ] Move the content of libr/*/TODO here
- [ ] linestyle?? for disassembly lines
- [ ] remove libr/vm and libr/db
- [ ] imho we should not implement this:
   - Implement BLOCK in r_core_sysenv_begin|end ()
- [ ] Deprecate CiU (remove) those APIs and dependencies!
- [ ] big-ssl.c big-gmp.c ...
- [ ] implement GMP in util/big.c
- [ ] [testing for primality](http://etutorials.org/Programming/secure+programming/Chapter+7.+Public+Key+Cryptography/7.5+Generating+a+Prime+Number+Testing+for+Primality/)

As per #5424.
