### ISSUE TITLE
Optimizations todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5506]
## Performance
- [ ] cons_visual_write() should do a single write instead of one per line
- [ ] Refactor get_sym() and so on...
- [ ] make elf/pe get_os() and others return const and not strdup
- [ ] RAnalValue must be static, not ref
- [ ] save memory and accelerate code analysis
- [ ] basicblock signatures must be just pointers to a big but

## Optimize /m
- [ ] search only using given file, not loading default library
- [ ] do not read each block byte per byte
- [ ] do not show repeated consecutive hits

As per #5424.
