### ISSUE TITLE
Future todos migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5507]
- [ ] memset0 the op before calling the plugin analysis -- not really that is a performance cost..
- [ ] rax2 -k by default?
- [ ] Add support for 'expect' like foo in rarun2
  - make rarun live in a lib.. or at least be usable from r2
- [ ] use centralized pubsub or memcached to sync data // redis?

- [ ] Realign flags when using project in debug mode

As per #5424.

**Comment by radare** [comment]
This is a complete mess of issue that requires discussion, verification that its done and cleaning up
