### ISSUE TITLE
Threads todo migrated from TODO.md

### ISSUE THREAD

**Issue by DanTheColoradan** [radare/radare2#5508]
- [x] implement non-threaded thread api (dummy one, when no support)
- [x] test w32 port
- [x] Implement a pure clone(2) backend
- [x] Added a threading pool super-api

## Debug information in binaries
- [x] dwarf, pdb, def, lib
  - from file, from section, ...
  - load symbols from .lib or .def (find signatures)
    .def -> .idt , .lib -> ar2idt
- [x] Useful information in the PDB format
  - programming language used (dwarf only?)
  - offset - file:line
  - elements { position, type, name, length, offset, delta }
  - types // using the r_anal vartype API (not yet implemented)
  - position = { inlined, global, local } enum
  - function = { visibility, position, type, calltype (cc), arglist, return }
  - visibility = { local, exported, qualified }
```
  Types {
  	// element types
  	array, bitfield, class, struct, union, enum, pointer
  	procedure, function, arglist, vtshape, fieldlist
  	
  	// data types
  	float, char, signed short, bool, address, ..
  }
  Type {
  	char, short, ushort, long, ulong, 
  }
```

As per #5424.

**Comment by radare** [comment]
All this stuff is already done. We can close the issue and remove all those points. I think is better to check if its done before opening new issues.

Also dont open issues with multiple stuff. Pdb info have nothing to do with threads

**Comment by Maijin** [comment]
@DanTheColoradan Well see already some can be removed ;)
