### ISSUE TITLE
[META] Make esil as accurate as debugging

### ISSUE THREAD

**Issue by oddcoder** [radare/radare2#5551]
This issue is to fix most bugs with esil and make is as close to debugging as possible
I will add more issues here once I encounter them
- [ ] Increase stack size for esil, I saw some binaries that overflow esil stack (unfortunately I dont have them any more)
- [ ] One another things is how interrupts are emulated (for example `int 3`).
- [ ]  what about something like `lea eax, ebp, jmp eax` then when I check memory at ebp in r2 I find it zeroed out.
- [ ] System calls too needs to be emulated.
- [ ] something like this
```
call sym.imp.malloc
cmp eax, 0
je exit:
.
.
.
.
exit: call sym.imp.exit
```
should we have some sort of symbolic execusion to initialize registers and memory to always take the longest path in code ? (similar to https://github.com/radare/radare2/issues/4722)

**Comment by monosource** [comment]
> Increase stack size for esil, I saw some binaries that overflow esil stack

I wonder if the necessary stack size can be automatically computed from static analysis. radare2 should not be wasteful.

Emulating "regular" instructions should be straightforward. There are problems when emulating interrupts and system calls. radare2 would need some sort of platform agnostic intermediary emulation for interrupts and system calls such that a i.e. MIPS interrupt can be emulated on x86, ARM, PPC etc. without the need to implement the emulation code on each platform.

You could take a look at how angr does it for syscalls https://github.com/angr/simuvex/tree/master/simuvex/procedures/syscalls

At the point in which you're starting to emulate interrupts, you're already implementing a VM/emulator for that platform.

**Comment by oddcoder** [comment]
I am sure that with out some kind of good emulation, ESIL will be almost useless against average programs (I am not talking about packed malware yet :P )

**Comment by radare** [comment]
and stack size of esil is actually 32, which is more than enough you can configure this in `esil.stacksize`, so if you get any 'stack overflow' or 'infinite loop' error when emulating esil is probably a bug in the esil expression

**Comment by radare** [comment]
there are scripts to emulate the syscalls, and yes, this will be done via RSyscall at some point, but we will never be able to emulate all the syscalls for all the kernels. but having most common ones ready should be a doable objective

**Comment by Maijin** [comment]
Well there are still plenty of bug unrelated to syscall/stack etc. remaining to get fixed, see also the @sushant94 script https://github.com/sushant94/esil-tests

**Comment by Maijin** [comment]
Tons of Basics one https://github.com/radare/radare2/issues/4952

**Comment by ret2libc** [comment]
This issue has been moved from radareorg/radare2 to radareorg/ideas as we are trying to clean our backlog and this issue has probably been created a long while ago. This is an effort to help contributors understand what are the actionable items they can work on, prioritize issues better and help users find active/duplicated issues more easily. If this is not an enhancement/improvement/general idea but a bug, feel free to ask for re-transfer to main repo. Thanks for your understanding and contribution with this issue.
