### ISSUE TITLE
[TRACKER] radare2 is not as cool as binaryninja

### ISSUE THREAD

**Issue by monosource** [radare/radare2#5568]
Link: https://binary.ninja/features.html
- [ ] Undo (see #3801)
- [x] Auto-updater
- [x] A cool graphical graph view
- [x] Hints to which registers get modified after a call (I believe this can be done with ESIL, but I'm not sure if there's an option to annotate in comments i.e. `call sym.func ; will change eax, ebx, ecx`
- [x] Handling switch statements in graph view
- [x] Automatic recognition of noreturn functions, to stop disassembly (#4929)
- [x] Better ESIL specification and design (see [blogpost on BNIL](https://binary.ninja/2017/04/17/BNIL-Series-Part-1.html))

binary.ninja:
![binja_graph](https://cloud.githubusercontent.com/assets/16955479/17830809/f77f7558-66df-11e6-8c0b-13108a21d487.png)

r2:
![r2_graph](https://cloud.githubusercontent.com/assets/16955479/17830810/f7863bcc-66df-11e6-8437-165170d59818.png)

That's it from what I can tell.

**Comment by Maijin** [comment]
Hum for switch statement, have you tried `anal.jmptbl` and all the stuff related ?

**Comment by Maijin** [comment]
`Undo` already exist for many operations, You need to be more specific on this.

**Comment by monosource** [comment]
`anal.jmptbl` indeed can analyze jump tables, but it doesn't connect the blocks. I guess it's because by default a basic block can only diverge into a `t` and `f` path?

Relevant image: `_8bd3_` seems to not go anywhere, when in fact it's the bb containing the `jmp` instruction.
![r2_jmptable](https://cloud.githubusercontent.com/assets/16955479/17833326/e22f9f6e-6722-11e6-8c5a-4369bb3f79e6.png)

The `undo` operation is simply not generic in r2. Like you said, you have `undo` for ops such as seek and write, but not for things like undoing flag renaming, for example.

**Comment by monosource** [comment]
@crowell you have some experience with binary ninja. What do you feel would be useful for r2?

**Comment by Maijin** [comment]
Undo stuff is duplicate of https://github.com/radare/radare2/issues/3801

**Comment by Maijin** [comment]
quite sure:
```
Hints to which registers get modified after a call (I believe this can be done with ESIL, but I'm not sure if there's an option to annotate in comments i.e. call sym.func ; will change eax, ebx, ecx
```
Is already done too.

**Comment by psifertex** [comment]
There is another useful feature shown in your screenshots show that might be worth mentioning: automatic identification of functions that don't return by propagating a no-return property. The r2 basic block at `0x8048c88` calls `explode_bomb` for example (which presumably calls exit or otherwise doesn't return itself), but then keeps disassembling unlike the BN graph which terminates after the call which is one of the reasons our layout ends up being a bit cleaner in this instance.

**Comment by radare** [comment]
this feature is already supported, but you need to specify that this function is noreturn type. we can improve this if we see that a function calls a noreturn function is also a noreturn one, but only if thats the only exit point

**Comment by jvoisin** [comment]
I think that @oddcoder's work on function's types recognition might help too.

**Comment by oddcoder** [comment]
fixed by
https://github.com/radare/radare2/commit/6c47f5a20d08760289004f2ae15612b9a4073e0a

**Comment by XVilka** [comment]
I would add here a better ESIL specification and design.

**Comment by radare** [comment]
whats currently done is not suposed to change at all, maybe i would just rewrite the implementation because its a bit spaguetti. and for mmx, fpu, … we are discussing about doing it as “esil coprocessors”, just as extensions of the original esil. this way we can split the implementation in several layers and identify which esil processors  we need to emulate some specific code.

**Comment by XVilka** [comment]
For Binary Ninja experts - please update the bug, I think they added a lot of features these days.

**Comment by radare** [comment]
i think the esil point can be marked as done, and the automatic noreturn..maybe its something to be done by a script. we already support noreturn points

**Comment by radare** [comment]
about the undo thing. thats very related to the task of syncing instances

**Comment by Maijin** [comment]
Closing here as the "undo all things" is covered. If someone is in the mood please reopen a new one with new features you want to see.
