### ISSUE TITLE
META - Project files

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6945]
# META - PROJECT

## Related

* [ ] Doc - TBD
* Tests - https://github.com/radare/radare2-regressions/blob/master/t/cmd_project
* Commands involved - `P?`
* [ ] BlogPost - TBD
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/core/cmd_project.c

## Information saved/loaded

* [ ] call-refs
* [ ] data-refs
    
## Various Fix

* [ ] Projects that were saved when using 'aaaa' do not work (with 'aaa' they work) [#6943](https://github.com/radare/radare2/issues/6943)

* [ ] Add a warning if prjname is different from the binary loaded
**INPUT**:
`r2 -p cat_project /bin/ls`
**EXPECTED_OUTPUT**:
`WARNING: prj.name changed: /bin/cat => /bin/ls, XXXXX`

* [ ] Deleted comments reappear on project open and automatic comments not deleted by CC- [#5445](https://github.com/radare/radare2/issues/5445)

* [ ] Flags of a project created in RW mode does not load upon opening the project in debug mode [#4955](https://github.com/radare/radare2/issues/4955)

* [ ] Save blobs in project file - Dump all the opened files in malloc:// into files to be opened for later when restoring the project.

* [ ] Multiple files loaded via `o [file] [offset]` are not restored properly from project [#6037](https://github.com/radare/radare2/issues/6037)

## Low Priority Enhancement

* [ ] Encrypt projects
* [ ] Sign projects
    
Idea is to test of presence of  gpg/gpg2 and spawn them at runtime.

**INPUT**:
`encrypt XXX`

**EXPECTED_OUTPUT**:
`Project encrypted/signed`
or
`gpg2 or gpg is not found`
