### ISSUE TITLE
META - Rahash2

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6946]
# META - RAHASH2

* [ ] Doc - TBD
* Tests - https://github.com/radare/radare2-regressions/blob/master/t.tools/rahash2/rahash2
* Command - `woD, woE, rahash2 -E, rahash2 -D`
* [ ] BlogPost - TBD
* .c involved:
    * https://github.com/radare/radare2/tree/master/libr/crypto

### Hashes

* [ ] Integrate the crca.c - The libr/hash/crca.c is not used anywhere, it must be used from r_hash to provide all those new checksums into rahash2

```
enum CRC_PRESETS {
     CRC_32=0,
     CRC_16,
     CRC_32_ECMA_267,
     CRC_32C,
     CRC_24,
     CRC_16_CITT,
     CRC_16_USB,
     CRC_16_HDLC,
     CRC_15_CAN,
     CRC_8_SMBUS
};
```
* [ ] Implement [murmur hash](https://github.com/salviati/slash/blob/master/hash.cc)
* [ ] Implement [Locality-sensitive hashing](https://en.wikipedia.org/wiki/Locality-sensitive_hashing)

### R_Crypto

- [ ] 3DES
- [ ] Serpent

### Decoders

* [ ] Add [custom alphabets](https://www.malwaretracker.com/decoder_base64.php) for woE woD baseXX using the key
`rahash2 -D base64 -S "ZYXW... -s "YWRtaW4="` 

### Compressions Algorithms
Add the Compressions Algorithm in rahash2

* [ ] zip
* [ ] lzma
* [ ] lznt1
* [ ] aPlib
* [ ] lzmat
* [ ] gzip (See `prg` command)

**Comment by wargio** [comment]
i'm thinking on integrating crc today..

**Comment by jack17529** [comment]
@Maijin sir for 2 days I will be busy because of exams in our college then I'll work hard.

**Comment by jack17529** [comment]
@Maijin sir where is r_hash file you are referring from which crca.c needs to be used please send link.

**Comment by Maijin** [comment]
It's not a file, it's name of radare plugin type, see how https://github.com/radare/radare2/blob/master/libr/hash/crc16.c is done, we need to use CRCA.c for the same purpose but for all those enum instead of CRC16 and CRC32 only.

**Comment by wargio** [comment]
@jack17529 actually i almost integrated that 2 days ago. i still haven't finished it
https://github.com/wargio/radare2/commit/f903c0d6c2560a49f78fd6d904bd89758cb1bd4b but if you want to finish it, just see my code.

**Comment by jack17529** [comment]
@wargio Sir I am looking at the code . Are you busy with something else?

**Comment by Maijin** [comment]
@jack17529 You can drop the "Sir" No need to be middle-age formal here 😆.

**Comment by jack17529** [comment]
@Maijin ok bro

**Comment by wargio** [comment]
@Maijin crca integrated.

**Comment by wargio** [comment]
I'm implementing blake2[s/b] but, we need a way to define the key output len since it's used defined.. how should i do this? @radare @Maijin

**Comment by Maijin** [comment]
`-l` is not used that could be used.

**Comment by ret2libc** [comment]
This issue has been moved from radareorg/radare2 to radareorg/ideas as we are trying to clean our backlog and this issue has probably been created a long while ago. This is an effort to help contributors understand what are the actionable items they can work on, prioritize issues better and help users find active/duplicated issues more easily. If this is not an enhancement/improvement/general idea but a bug, feel free to ask for re-transfer to main repo. Thanks for your understanding and contribution with this issue.
