### ISSUE TITLE
META - Zignature

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6947]
# META * RAHASH2

* [ ] Doc * TBD
* Tests * https://github.com/radare/radare2-regressions/blob/master/t/cmd_zignature
* Command * `z?`
* [ ] BlogPost * http://radare.today/posts/zignatures/
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/core/cmd_zign.c

## Fixes

* [ ] z/ doesn't restores flag name [#728](https://github.com/radare/radare2/issues/728)
* [ ] Bug when using "." (invalid offset detected)
* [ ] "."  is replaced by 0

```
zn bios
zb PCI_WriteWord_SSE 668be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4
zb PCI_WriteWord_SSE_gen ..8be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4
zb PCI_WriteWord_SSE_gen2  .8be166c1ec10660f73f902660fc4cc00660f73f902660fc4c900668be266c1ec10660f73fa02660fc4d400660f73fa02660fc4d2008bc8baf80c660d000000806683e0fc66efbafc0c83e10203d18bc3ef660f7ed2660f73da04660f7ec9660f73d904660fc5e400660f73dc02ffe4 # This rule replaced "." by "0" (bug)
zn-
.z/ section..text section..text+1074039
? sign.bios.b.PCI_WriteWord_SSE
#7000:0344  correct
? sign.bios.b.PCI_WriteWord_SSE_gen
#10000:0376 incorrect
```

* [ ] Bug: In previous example, the zignature counter detection still display 1 but actually found 2
* [ ] Bug: bitmask doesn't work `zb blabla 992233 ff00ff`
* [ ] zg shuold walk the basic blocks, but the function length (otherwise we will be comparing with data inside the function, mixed functions can share basic blocks huge functions, when in fact they are just small ones with far nodes)
* [ ] Zignatures with zero bytes  [#5688](https://github.com/radare/radare2/issues/5688)
* [ ] A check on function 0x4010A5 in the target binary, where various calls to msvcrt._strlen and msvcrt._sprintf etc. happen, showed that the zignatures either did not match or were not renamed accordingly. [#5688](https://github.com/radare/radare2/issues/5718)

## Enhancements

* [ ] Honor r_search in zignature matching
* [ ]  Refact some commands name/function see https://gist.github.com/jroimartin/23421d6800684f4c99cb8884679a0939
* [ ] New commands aim to be consistent with flag management (`zs`)
    - `zs`: display zignspaces (status per zignspace)
    - `zs zignspace`: select zignspace
    - `zs *`: select all zignspace
    - `zs- zignspace`: delete zignspace
    - `zs-*`: delete all zignspaces 
* [ ] Loading the zig file in the target binary works but spits out a lot of garbage text [#5718](https://github.com/radare/radare2/issues/5718)
* [ ] Add Warning about invalid char such as `?` in the signature
* [ ] Add Warning when the name is too long
* [ ] Do not hardcode preludes in https://github.com/radare/radare2/blob/master/libr/core/cmd_search.c#L213 add zignature equivalent: 
```
# Signatures
zn prelude
zb prelude_ppc_A 7c0802a6
zb prelude_arm_16_A f0b5
zb prelude_arm_32_A 00482de9
zb prelude_arm_64_A f657bda9
zb prelude_arm_64_B fd7bbfa9
zb prelude_arm_64_C fc6fbea9
zb prelude_arm_64_D 27bd00
zb prelude_x86_32_A 8bff558bec
zb prelude_x86_32_B 5589e5
zb prelude_x86_32_C 558bec
zb prelude_x86_64_A 554889e5
zb prelude_x86_64_B 55488bec
zn-
```
* [ ] Use Zignature for WinMain detection [#832](https://github.com/radare/radare2/issues/832)
* [ ] Flirt to Zignature converter (`zfz flirt_file > zignatures.sig`)
* [ ] Signature files must be in SDB to accelerate loading times (`zod filename`: load zignatures from sdb file)
* [ ] Load compressed zignatures (`zoz filename`: load zignatures from gzip file)
```

## Documentation

* [ ] Add help about "." in the rules because it's different from flirt
* [ ] Add Help/documentation on head signatures
* [ ] Add Help/documentation on func signatures

**Comment by jroimartin** [comment]
I'm working on a new implementation of zignatures.

**Comment by jroimartin** [comment]
Related PR: https://github.com/radare/radare2/pull/6997

**Comment by XVilka** [comment]
- [ ] zF command - FLIRT - add 'scan' command, like in Yara
- [ ] zF - do not scan by default
- [ ] zF - show the status of FLIRT signatures in 'z' commands
- [ ] zb - arguments support + documentation in a book
- [ ] z/ - search in '[0 ; $s]' range by default
- [ ] bug for AVR + z/ on linux 32bit

**Comment by XVilka** [comment]
Would be nice to have the feature of storing function metainformation in signatures, like not only name, but also function size (or multiple blocks, in case of function split in chunks), local flags inside the function, function arguments and local variables, function comments.

**Comment by XVilka** [comment]
@sivaramaaa here you can have an interest in the part of the zignature that will allow to save/load the function arguments and their types. I think it is heavily related to your task.

**Comment by securitykitten** [comment]
Reading through this list of zignature ideas and I think I can help with the function preludes.

In CSE's assemblyline tool they have a Binary Ninja script that will do a linear sweep based upon a pretty comprehensive list of preludes.  Highlighted here -> https://bitbucket.org/cse-assemblyline/alsvc_binja/src/31f03aec9afde2e9a610381ed8f1e6164a25e647/binja.py?at=master&fileviewer=file-view-default#binja.py-391

These could probably be used to create a zignature list for functions.

**Comment by radare** [comment]
many of those things are done, soeone should update the ticks
