### ISSUE TITLE
META - Ragg2

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6949]
# META - Ragg2

* [ ] Doc : TBD
* Tests : https://github.com/radare/radare2-regressions/tree/master/t.tools/ragg2-cc and https://github.com/radare/radare2-regressions/tree/master/t.tools/ragg2
* Command : `g, ragg2, ragg2-cc`
* [ ] BlogPost : TBD 
* .c involved:
    * https://github.com/radare/radare2/tree/master/binr/ragg2

## Fixes

* [ ] `Cannot assemble 'push'` https://github.com/radare/radare2/issues/268

```
write@syscall(4);
exit@syscall(1);

main@global(128) {
    .var0 = "hi!\n";
    .var1 = 1;
    .var2 = 2;
    if (.var1 < .var2) {
        write(1,.var0, 4);
    }
    exit(0);
}
```

```
ragg2 test.r
Unknown opcode (cmp)
Unknown opcode (cmp)
Unknown opcode (cmp)
fail assembling
r_egg_assemble: invalid assembly
zsh: exit 1     ragg2 test.r
```

* [ ] `Cannot assemble 'jz __end_0_2_1' at line 204`   https://github.com/radare/radare2/issues/269
* [ ] ragg2 encoding is not working https://github.com/radare/radare2/issues/1267
* [ ] Multiple strings in ragg2 egg files doesn't work https://github.com/radare/radare2/issues/3235
## Enhancements

* [ ] Merge ragg2 and ragg2-cc
* [ ] Use [MPC](https://github.com/orangeduck/mpc) for Ragg2 parsing, much better than doing our own syntax parser or bison/yacc
* [ ] Implement labels
* [ ] `g` command is confusing,  Will be good to have a way to create payloads like ragg2 does but using g.. which should be already possible but it's pretty confusing and hard to use because it requires to batch stages and compile them back to get the result which is not intuitive for testing multiple changes.
* [ ] Support ragg2-cc with sys/ndk-gcc 
* [ ] Support ragg2-cc in Termux

**Comment by SooryaN** [comment]
I'd like to work on using MPC for Ragg2 parsing

**Comment by ZhangZhuoSJTU** [comment]
Seems that labels are implemented ? 
Following is the source code:
```
write@syscall(4);

main@global(128, 128) {
    write(1, "test", 4);
    goto (aaa);
    exit(0);
    :aaa:
}
```
And I use the command to see the assembly code 
```
ragg2 -s -b 32 -a x86 simple.r
```
With the output:
```
.global main
main:
  push ebp
  mov ebp, esp
  sub esp, 384
# rcc_fun 1 (write)
  push 4
# encode filtered string (test) (write)
  mov [ebp+24], 0x74736574
  mov [ebp+28], 0x0
  mov [ebp+32], 0
  lea eax, [ebp+24]
  mov [ebp+20], eax
  push [ebp+20]
  push 1
# set syscall args
  mov ebx, [esp]
  mov ecx, [esp+4]
  mov edx, [esp+8]
# syscall
  mov eax, 4
  push eax
  int 0x80
  add esp, 4
  add esp, 12
# rcc_fun 1 (goto)
  push aaa
  jmp aaa
# rcc_fun 1 (exit)
  push 0
# call in mode 0
  call exit
  add esp, 4
aaa:
  add esp, 384
  pop ebp
  ret
``` 
I have read the source code and, actually, the code implements labels in a very tricky and clever way.

Or, did I misunderstand the meaning of __"Implement labels"__, hah

**Comment by Maijin** [comment]
See https://github.com/radare/radare2/issues/271 ?

**Comment by ZhangZhuoSJTU** [comment]
According to the radare2 book, the syntax of labels should be:
```
:label_name:
```
but not 
```
label_name:
```

or, is the latter syntax needed ? If so,  I could work on it

**Comment by Maijin** [comment]
if the issue mentionned in #271 is solve (given the correct syntax) then we can check as done, could you try?

**Comment by ZhangZhuoSJTU** [comment]
Of course,  maybe half an hour later, for I am dealing with  something else.

**Comment by ZhangZhuoSJTU** [comment]
Yes, it's solved. Following is the test.
```
$ cat label_right.r
main@global(128, 128) {
        :label:
        :label:
        goto(label);
}
```
```
$ ragg2 -s -b 32 -a x86 label_right.r

.global main
main:
  push ebp
  mov ebp, esp
  sub esp, 384
label:
label:
# rcc_fun 1 (goto)
  jmp label
  add esp, 384
  pop ebp
  ret
```
And, now, even the wrong syntax, there will not be errors. Although, the labels will be ignored.
```
$ cat label_wrong.r
main@global(128, 128) {
        label:
        label:
        goto(label);
}
```
```
$ ragg2 -s -b 32 -a x86 label_wrong.r

.global main
main:
  push ebp
  mov ebp, esp
  sub esp, 384
# rcc_fun 1 (goto)
  jmp label
  add esp, 384
  pop ebp
  ret
```

**Comment by Maijin** [comment]
Checked then, thanks for verifying. While you're at it, feel free to add tests in r2r for this functionality :).

**Comment by ZhangZhuoSJTU** [comment]
Additionally, the -x option of ragg2 goes wrong on my computer. Should I open a new issue to report it, or just report here ?

**Comment by radare** [comment]
Well if you prefix a line with : it will inline into the final assembly code so its not needed to do that in ragg2 because its already done in rasm2 and ragg2 can pass thru

**Comment by radare** [comment]
You maybwant to add tests but imho its ok as it is

**Comment by ret2libc** [comment]
This issue has been moved from radareorg/radare2 to radareorg/ideas as we are trying to clean our backlog and this issue has probably been created a long while ago. This is an effort to help contributors understand what are the actionable items they can work on, prioritize issues better and help users find active/duplicated issues more easily. If this is not an enhancement/improvement/general idea but a bug, feel free to ask for re-transfer to main repo. Thanks for your understanding and contribution with this issue.
