### ISSUE TITLE
META - ROP

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6950]
* [ ] Doc : TBD
* Tests : https://github.com/radare/radare2-regressions/blob/master/t/cmd_rop
* Command : `/R`
* [ ] BlogPost : TBD
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/core/cmd_search_rop.c

# Enhancement

* [ ] Rop gadget classification
Classify them in those categories:

```
NOP                         
JUMP            EIP = AddrReg + Offset
MoveReg         OutReg = InReg
LoadConst       OutReg = Value
Arithmetic      OutReg = InReg1 <op> InReg2
LoadMem         OutReg = [AddrReg + Offset]
StoreMem        [AddrReg + Offset] = InReg
ArithmeticLoad      OutReg = OutReg <op> [AddrReg + Offset]
ArithmeticStore     [AddrReg + Offset] = [AddrReg + Offset] <op> InReg
```
See merged PR here - #5448 #5481 #5515 #5531 

* [ ] Use SDB to store ROP - https://github.com/radare/radare2/issues/5162
* [ ] Rop search improvement - https://github.com/radare/radare2/issues/4284
* [ ] ROP Search using ESIL - https://github.com/radare/radare2/issues/2612
* [ ] Auto ropper https://github.com/radare/radare2/issues/1708
* [ ] Primitive detecting (pivot, leak, write-what-where, etc.) https://github.com/radare/radare2/issues/1708
* [ ] Building a complete ROPChain - https://github.com/radare/radare2/issues/1131

**Comment by XVilka** [comment]
This tool also looks good https://github.com/Boyan-MILANOV/ropgenerator

**Comment by ret2libc** [comment]
This issue has been moved from radareorg/radare2 to radareorg/ideas as we are trying to clean our backlog and this issue has probably been created a long while ago. This is an effort to help contributors understand what are the actionable items they can work on, prioritize issues better and help users find active/duplicated issues more easily. If this is not an enhancement/improvement/general idea but a bug, feel free to ask for re-transfer to main repo. Thanks for your understanding and contribution with this issue.
