### ISSUE TITLE
META - ARM

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6953]
# Related

* Tests : https://github.com/radare/radare2-regressions/tree/master/t.anal/arm ; https://github.com/radare/radare2-regressions/tree/master/t.asm/arm
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/anal/p/anal_arm_cs.c
    * https://github.com/radare/radare2/blob/master/libr/asm/p/asm_arm_cs.c

## Regprofile 
* [ ] Add CPSR bits for ARM32 & ARM64 https://github.com/radare/radare2/issues/6107 
* [ ] Improve ARM regprofile https://github.com/radare/radare2/issues/6500
* [ ] ARM Register in Thumb mode https://github.com/radare/radare2/issues/2557

## ARM vs Thumb
* [ ] r_core_seek_archbits produces wrong results cause usage of oldbits https://github.com/radare/radare2/issues/6922
* [ ] Seemingly inconsistent disassembly of a Thumb instruction https://github.com/radare/radare2/issues/6741 

## ARM ESIL
* [ ] Complete ARM64 ESIL
	`0x1000181f0      3c7f4093       TODO,Sxtw x28, w25`
* [ ] stm/ldm should be post, not pre increment https://github.com/radare/radare2/issues/6389

## ARM Assembler

* [ ] Trouble assembling thumb pop with register range notation https://github.com/radare/radare2/issues/3096 
* [ ] ARM assembler doesn't do LDR/STR with shifts https://github.com/radare/radare2/issues/6477

## ARM Analysis

* [ ] Using Thumb function pointers for data xrefs https://github.com/radare/radare2/issues/6697
* [ ] ELF .dword not always recognized by aaa https://github.com/radare/radare2/issues/6653
* [ ] Handle LOCK instructions in ARM64 https://github.com/radare/radare2/issues/6172
* [ ] Comments are off with ARM's SP https://github.com/radare/radare2/issues/4957
* [ ] Issue with address calculation for ARM with -d (debug) flag https://github.com/radare/radare2/issues/4487
* [ ] Analyze [mov,add,sub,..] pc as JMP instructions in ARM (ESIL and RAnalOP)
	`add pc, pc, 4` -> `jmp $$ + 8`. 
* [ ] ARM debugger defines endian and cpu mode depending on CPSR https://github.com/radare/radare2/issues/518
