### ISSUE TITLE
META - GRAPH

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6967]
# Related

* DOC: TBD
* BLOG: TBD
* Tests : https://github.com/radare/radare2-regressions/blob/master/t/cmd_graph
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/core/graph.c

# Fixes

* [ ] Fixing overlapping edges and nodes in graph mode https://github.com/radare/radare2/issues/6011
* [ ] Invalid output in graph mode when instruction overlapping (jump in the middle of instr) https://github.com/radare/radare2/issues/6012
* [ ] Goto shortcuts are not shown in Graph Mode Summary view https://github.com/radare/radare2/issues/6018
    
# Enhancements

## Graph Debugger

* [ ] Show stack
* [ ] Show registry
* [ ] Relocate analysis data automatically (configurable via eval variable)

## Graph Cursor

* [ ] Ability to have a cursor in this mode - to follow calls https://github.com/radare/radare2/issues/1566
* [ ] Ability to have a cursor in this mode - to escape calls https://github.com/radare/radare2/issues/1566

## Graph Diffing

* [ ] radiff2 -g should output in ascii art too https://github.com/radare/radare2/issues/3508
* [ ] radiff2 -g color issues https://github.com/radare/radare2/issues/3614

## Interactivity

* [ ] Focus node with mouse click in ascii-art graph
* [ ] Grouping nodes https://github.com/radare/radare2/issues/2952

## New commands

* [ ] Add a ag sub-command that should return all functions in graphviz  https://github.com/radare/radare2/issues/4627
* [ ] Add "agc $$" option or subcommand to graph recursively
* [ ] Add command to export graph layout https://github.com/radare/radare2/issues/5210
* [ ] Output Graph structure to graphviz dot format
We can already dump function graphs and callgraphs to dot format, but not using the graph API used for ascii art rendering. The graph API should be exposed to bindings and r2 commandline, so anyone can create a graph with its contents and render it.. this way we can also do code graphdiffing in ascii art. and enable python/js to use that

## Colorization

* [ ] Colorize head and tails basic blocks in function graph (graphviz) https://github.com/radare/radare2/issues/4463
* [ ] Colourize nodes that has been traced (like in the webui)

## Switch Statements

* [ ] Enable switch statements by default

## Optimization/Refactoring

* [ ] RAGraph as a field of RAnalFunction https://github.com/radare/radare2/issues/2976
* [ ] Optimize graph by removing single instruction jmp basic blocks #5744
