### ISSUE TITLE
META - RADIFF2

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#6971]
# Related

* DOC: TBD
* BLOG: TBD
* Tests : https://github.com/radare/radare2-regressions/blob/master/t.tools/radiff2/radiff2
* .c involved:
    * https://github.com/radare/radare2/blob/master/libr/core/cmd_cmp.c
    * https://github.com/radare/radare2/blob/master/binr/radiff2/radiff2.c

# Fixes

* [ ] radiff2 -g color issues https://github.com/radare/radare2/issues/3614
* [ ] radiff2 malware diffing bad results https://github.com/radare/radare2/issues/5362

# Enhancement

* [ ] Do not autoname when radiff2 -C
* [ ] radiff2 -jC - JSON output for the graphdiff
* [ ] radiff2 -x binary1 binary2 should print diff in readable hex output https://github.com/radare/radare2/issues/561
* [ ] Obey colourscheme in diff graphs https://github.com/radare/radare2/issues/2141
* [ ] Implement -r mode for radiff2 -C
* [ ] radiff2 -g should output in ascii art too https://github.com/radare/radare2/issues/3508
* [ ] Colours radiff2 graphdiff output https://github.com/radare/radare2/issues/6021
* [ ] radiff2 -u should support buffers of different size ; it is currently chopping the buffers to R_MIN(lenA, lenB)

# Compatibility with other softwares

* [ ] Output for BinNavi https://github.com/radare/radare2/issues/3873
* [ ] Support all analysis info required for Diaphora https://github.com/radare/radare2/issues/2742

**Comment by XVilka** [comment]
See also https://github.com/radare/radare2/issues/9128

**Comment by trufae** [comment]
take ideas to diff assembly https://github.com/simonlindholm/asm-differ
