### ISSUE TITLE
META - Console Interface improvements

### ISSUE THREAD

**Issue by XVilka** [radare/radare2#8672]
- [ ] Visual panels layout load/save option https://github.com/radare/radare2/issues/8215
 - [ ] Add a popup console "widget" https://github.com/radare/radare2/issues/8476
 - [ ] Split-view visual hex diff mode for radiff2 https://github.com/radare/radare2/issues/8115
 - [ ] Differentiate user from system comments https://github.com/radare/radare2/issues/7982
 - [ ] META: Better support for Unicode, RTL and BiDI https://github.com/radare/radare2/issues/2032
 - [ ] Support custom color palettes and non-byte sized pixel colors https://github.com/radare/radare2/issues/7638
 - [ ] Separate command line history for SDB shell https://github.com/radare/radare2/issues/7649
 - [ ] API and commands for TABLE "widget" (like for graphs) https://github.com/radare/radare2/issues/7519
 - [ ] Cursor mode (selecting lines) in ASCII/Unicode graph https://github.com/radare/radare2/issues/7248
 - [ ] Show minigraph together with the graph https://github.com/radare/radare2/issues/7182
 - [ ] Context-dependent colors for comments https://github.com/radare/radare2/issues/5716
 - [ ] Two dimensional Visual mode https://github.com/radare/radare2/issues/7017
 - [ ] Enhance the VE (visual color scheme editor) https://github.com/radare/radare2/issues/3692
 - [ ] Add support for bold attribute in RCons https://github.com/radare/radare2/issues/4214
 - [ ] META: Autocompletion https://github.com/radare/radare2/issues/3033
 - [ ] Improve disassembly reflines https://github.com/radare/radare2/issues/3670
 - [ ] Dotted lines for conditional jumps https://github.com/radare/radare2/issues/204
 - [ ] Different colors for local (in-function) jump arrows and global (from function) jump https://github.com/radare/radare2/issues/333
 - [ ] Command/API to set particular node background https://github.com/radare/radare2/issues/8588

**Comment by radare** [comment]
i think we shuold have only one visual menu for browsing everything. this is instead of having VB for classes Ve for eval vars.. have a key that enters a menuto choose those, so we can savesome keys in visual and extend all the browsing features in a single visual menu.

- browse bin info
- browse dwarf  (list all files, select line, seek to offset)
- browse meta info
- browse code type information
- browse classes
- browse flags
- browse eval vars
- browse xrefs
- browse functions
- …

i suggest to use VB for this ‘because its about browsing’.

i would just keep the V_ because the hud is handy

thoughs?

**Comment by XVilka** [comment]
@radare I agree, will simplify code a lot. Not sure if you need to make it a "menu" though, keeping the "direct" calls is important.

**Comment by XVilka** [comment]
@cyanpencil this is all yours, don't forget it :D

**Comment by XVilka** [comment]
Related https://github.com/radare/radare2/pull/12693

**Comment by ret2libc** [comment]
This issue has been moved from radareorg/radare2 to radareorg/ideas as we are trying to clean our backlog and this issue has probably been created a long while ago. This is an effort to help contributors understand what are the actionable items they can work on, prioritize issues better and help users find active/duplicated issues more easily. If this is not an enhancement/improvement/general idea but a bug, feel free to ask for re-transfer to main repo. Thanks for your understanding and contribution with this issue.
